/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include <string.h>
#include "EEROM.h"
#include "I2C.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
//	char str[32] = "!HELLO!";

	SystemInit();
	EEPROM_init();
	UartInit(BAUD_9600);
	char str[70] = "!HELLO!";
	int ch ;

	do
	{
		sprintf(str,"Enter the choice :- \r\n1.Data Write on EEPROM\r\n2.Data Read from EEPROM\n:");
		UartPuts(str);

		sscanf(str,"%d",&ch);
		UartGets(str);
		//UartPuts("Enter the string :  \r\n");

		switch(ch)
		{
			case 1 :
				sprintf(str,"Enter string\n");
				UartPuts(str);
				UartGets(str);
				sscanf(str,"%s",str);
				EEPROM_write(0X0020,(uint8_t*)str,12);
				break;

			case 2 :
				EEPROM_read(0X0020,(uint8_t*)str,12);
				UartPuts(str);
				sprintf(str,"\n\r");
				UartPuts(str);
				break;
		}
	}while(ch != 0);

	return 0;
}
